LIST p=18F4550 				;directive to define processor
#include<P18F4550.INC> 	;processor specific variable definitions
 
    	;CONFIG1L dir 300000h 		20
		CONFIG	PLLDIV=1	 	; 
		CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA 	
		CONFIG	USBDIV=2

		;CONFIG1H dir 300001h	   08
		CONFIG	FOSC=INTOSCIO_EC	;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
		CONFIG	FCMEN=OFF       ;DESHABILITDO EL MONITOREO DEL RELOJ
		CONFIG	IESO=OFF
		;CONFIG2L DIR 300002H	   	38
		CONFIG	PWRT=ON         ;PWRT HABILITADO
		CONFIG  BOR=OFF		 	;BROWN OUT RESET DESHABILITADO
		CONFIG BORV=3			;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
		CONFIG	VREGEN=ON	 	;REULADOR DE USB ENCENDIDO
		;CONFIG2H DIR 300003H	   	1E
		CONFIG	WDT=OFF         ;WACH DOG DESHABILITADO
		CONFIG WDTPS=32768      ;TIMER DEL WATCHDOG 
		;CONFIG3H DIR 300005H 	   	81
		CONFIG	CCP2MX=ON	 	;CCP2 MULTIPLEXADAS CON RC1	
		CONFIG	PBADEN=OFF      ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
		CONFIG  LPT1OSC=OFF	 	;TIMER1 CONFIURADO PARA OPERAR EN BAJA POTENCIA
		CONFIG	MCLRE=ON        ;MASTER CLEAR HABILITADO
		;CONFIG4L DIR 300006H	   	81
		CONFIG	STVREN=ON	 	;SI EL STACK SE LLENA CAUSE RESET		
		CONFIG	LVP=OFF		 	;PROGRAMACIÒN EN BAJO VOLTAJE APAGADO
		CONFIG	ICPRT=OFF	 	;REGISTRO ICPORT DESHABILITADO
		CONFIG	XINST=OFF  		;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO
		;CONFIG5L DIR 300008H 		0F
		CONFIG	CP0=OFF		 	;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
		CONFIG	CP1=OFF         ;NO ESTAN PROTEGIDOS
		CONFIG	CP2=OFF		 
		CONFIG	CP3=OFF
		;CONFIG5H DR 300009H  		80
		CONFIG	CPB=ON		 	;SECTOR BOOT ESTA PROTEGIDO
		CONFIG	CPD=OFF		 	;EEPROM N PROTEGIDA
		;CONFIG6L DIR 30000AH 		0F
		CONFIG	 WRT0=OFF	 	;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
		CONFIG	 WRT1=OFF
		CONFIG	 WRT2=OFF
		CONFIG	 WRT3=OFF

		;CONFIG6H DIR 30000BH		A0
		CONFIG	 WRTC=OFF	 	;CONFIGURACION DE REGISTROS NO PROTEGIDO
		CONFIG	 WRTB=ON	 	;BLOQUE BOOTEBLE NO PROTEGIDO
		CONFIG	 WRTD=OFF	 	;EEPROMDE DATOS NO PROTGIDA

		;CONFIG7L DIR 30000CH		0F
		CONFIG	 EBTR0=OFF	 	;TABLAS DE LETURA NO PROTEGIDAS
		CONFIG	 EBTR1=OFF
		CONFIG	 EBTR2=OFF
		CONFIG	 EBTR3=OFF

		;CONFIG7H DIR 30000DH		40
		CONFIG	 EBTRB=OFF	 	;TABLAS NO PROTEGIDAS

 	CBLOCK 0x0			; PARA VARIABLES
 
 	ENDC 
 
 	org 0					; DIRECCION 0 DE LA MEMORIA
 
;-------------------------------------------------------------	
; CONFIGURACION DE PUERTOS
	
    		clrf TRISA  			; 
		clrf TRISB
 		clrf TRISC 			; 
    		clrf TRISD
    		clrf TRISE

;//------------------------------------------------------
; ahora viene la deshabilitación de modulos (pheriperals)
;*******************************************************
 		clrf ADCON0 			; desactiva el CAD
 		movlw 0xf 
 		movwf ADCON1 			; todas digitales

 		movlw 0x07 
 		movwf CMCON 			;desactiva el modulo comparador
 	
 	
;//-------------------------------------------
; CUERPO DE PROGRAMA

		movlw	0xff ;MUEVE LA CONSTANTE "FF" HACÍA EL REGISTRO DE TRABAJO (W)
		movwf	TRISA ;MUEVE LO QUE HAY EN EL REGISTRO DE TRABAJO Y LO MANDA A TRISA (DEFINE SI EL PUERTO ES ENTRADA O SALIDA)
		movlw	0x00 ;MUEVE LA CONSTANTE "00" HACÍA EL REGISTRO DE TRABAJO (W)
		movwf	TRISB ;MUEVE LO QUE HAY EN EL REGISTRO DE TRABAJO Y LO MANDA A TRISB (DEFINE SI EL PUERTO ES ENTRADA O SALIDA)
		
	INI     movf    PORTA,0 ;MUEVE LO QUE HAY EN W HACÍA PORTA 
		movwf   PORTB ;MUEVE LO QUE HAY EN W HACÍA PORTB
		bra	INI ; REGRESA A "INI"
		END



