LIST p=18F4550 				;directive to define processor
#include<P18F4550.INC> 	;processor specific variable definitions
    	;CONFIG1L dir 300000h 		20
		CONFIG	PLLDIV=1	 	; 
		CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA 	
		CONFIG	USBDIV=2

		;CONFIG1H dir 300001h	   08
		CONFIG	FOSC=INTOSCIO_EC	;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
		CONFIG	FCMEN=OFF       ;DESHABILITDO EL MONITOREO DEL RELOJ
		CONFIG	IESO=OFF
		;CONFIG2L DIR 300002H	   	38
		CONFIG	PWRT=ON         ;PWRT HABILITADO
		CONFIG  BOR=OFF		 	;BROWN OUT RESET DESHABILITADO
		CONFIG BORV=3			;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
		CONFIG	VREGEN=ON	 	;REULADOR DE USB ENCENDIDO
		;CONFIG2H DIR 300003H	   	1E
		CONFIG	WDT=OFF         ;WACH DOG DESHABILITADO
		CONFIG WDTPS=32768      ;TIMER DEL WATCHDOG 
		;CONFIG3H DIR 300005H 	   	81
		CONFIG	CCP2MX=ON	 	;CCP2 MULTIPLEXADAS CON RC1	
		CONFIG	PBADEN=OFF      ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
		CONFIG  LPT1OSC=OFF	 	;TIMER1 CONFIURADO PARA OPERAR EN BAJA POTENCIA
		CONFIG	MCLRE=ON        ;MASTER CLEAR HABILITADO
		;CONFIG4L DIR 300006H	   	81
		CONFIG	STVREN=ON	 	;SI EL STACK SE LLENA CAUSE RESET		
		CONFIG	LVP=OFF		 	;PROGRAMACIÒN EN BAJO VOLTAJE APAGADO
		CONFIG	ICPRT=OFF	 	;REGISTRO ICPORT DESHABILITADO
		CONFIG	XINST=OFF  		;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO
		;CONFIG5L DIR 300008H 		0F
		CONFIG	CP0=OFF		 	;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
		CONFIG	CP1=OFF         ;NO ESTAN PROTEGIDOS
		CONFIG	CP2=OFF		 
		CONFIG	CP3=OFF
		;CONFIG5H DR 300009H  		80
		CONFIG	CPB=ON		 	;SECTOR BOOT ESTA PROTEGIDO
		CONFIG	CPD=OFF		 	;EEPROM N PROTEGIDA
		;CONFIG6L DIR 30000AH 		0F
		CONFIG	 WRT0=OFF	 	;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
		CONFIG	 WRT1=OFF
		CONFIG	 WRT2=OFF
		CONFIG	 WRT3=OFF

		;CONFIG6H DIR 30000BH		A0
		CONFIG	 WRTC=OFF	 	;CONFIGURACION DE REGISTROS NO PROTEGIDO
		CONFIG	 WRTB=ON	 	;BLOQUE BOOTEBLE NO PROTEGIDO
		CONFIG	 WRTD=OFF	 	;EEPROMDE DATOS NO PROTGIDA

		;CONFIG7L DIR 30000CH		0F
		CONFIG	 EBTR0=OFF	 	;TABLAS DE LETURA NO PROTEGIDAS
		CONFIG	 EBTR1=OFF
		CONFIG	 EBTR2=OFF
		CONFIG	 EBTR3=OFF

		;CONFIG7H DIR 30000DH		40
		CONFIG	 EBTRB=OFF	 	;TABLAS NO PROTEGIDAS

 	CBLOCK 0x0			; PARA VARIABLES
 
 	ENDC 
 
 	org 0					; DIRECCION 0 DE LA MEMORIA 
;-------------------------------------------------------------	
; CONFIGURACION DE PUERTOS	
    		clrf TRISA  			; 
		clrf TRISB
 		clrf TRISC 			; 
    		clrf TRISD
    		clrf TRISE
;//------------------------------------------------------
; ahora viene la deshabilitación de modulos (pheriperals)
;*******************************************************
 		clrf ADCON0 			; desactiva el CAD
 		movlw 0xf 
 		movwf ADCON1 			; todas digitales

 		movlw 0x07 
 		movwf CMCON 			;desactiva el modulo comparador 	
;//-------------------------------------------
; CUERPO DE PROGRAMA
		CONT	EQU	0x0F
		R_1M	EQU	0x10
		R2_1M	EQU	0x11
		
		MOVLW	0x03
		MOVWF	TRISA		
		MOVLW	0x00
		MOVWF	TRISB		
		BRA	PREG_0		
	
	;ESTA ES LA TABLA CON LOS
	;VALORES DEL 1 AL 15
	TABLA	ADDWF	PCL, 1
		RETLW	0x3F ;0		
		RETLW	0x06 ;1
		RETLW	0x5B ;2
		RETLW	0x4F ;3
		RETLW	0x66 ;4
		RETLW	0x6D ;5
		RETLW	0x7D ;6
		RETLW	0x07 ;7
		RETLW	0xFF ;8
		RETLW	0x6F ;9
		RETLW	0x77 ;10
		RETLW	0x7C ;11
		RETLW	0x39 ;12
		RETLW	0x5E ;13
		RETLW	0x79 ;14
		RETLW	0x71 ;15
		
	PREG_0	MOVF	PORTA,0
		SUBLW	0x00
		BTFSS	STATUS, Z
		BRA	PREG_1
		BRA	CONT_DE			
	PREG_1	MOVF	PORTA,0
		SUBLW	0x01
		BTFSS	STATUS,Z
		BRA	PREG_2
		BRA	CON_OCT
	PREG_2	MOVF	PORTA,0
		SUBLW	0x02
		BTFSS	STATUS,Z
		BRA	PREG_3
		BRA	CON_HEX
	PREG_3	MOVF	PORTA,0
		SUBLW	0x03
		BTFSS	STATUS,Z
		BRA	PREG_0
		BRA	RESET_P	
	;-------------------------------------------------
	;ESTE CÓDIGO HACE CONTEO DECIMAL
	CONT_DE CLRF	CONT
	INI_DEC	MOVF	CONT,0
		CALL	TABLA
		MOVWF	PORTB
		CALL	RET_1S ;RETARDO DE 1 SEG   
		MOVF	CONT,0
		SUBLW	0x12
		BTFSS	STATUS,Z
		BRA	INC_DEC
		BRA	PREG_0		
	INC_DEC	INCF	CONT,1
		INCF	CONT,1
		BRA	INI_DEC
	;-------------------------------------------------
	
	;-------------------------------------------------
	;ESTE CÓDIGO HACE CONTEO OCTAL
	CON_OCT CLRF	CONT
	INI_OCT	MOVF	CONT,0
		CALL	TABLA
		MOVWF	PORTB
		CALL	RET_1S ;RETARDO DE 1 SEG   
		MOVF	CONT,0
		SUBLW	0x0E
		BTFSS	STATUS,Z
		BRA	INC_OCT
		BRA	PREG_0		
	INC_OCT	INCF	CONT,1
		INCF	CONT,1
		BRA	INI_OCT
	;-------------------------------------------------		
	CON_HEX MOVLW	0x1E
		MOVWF	CONT
	SEGUIR	MOVF	CONT,0
		CALL	TABLA
		MOVWF	PORTB
		CALL	RET_1S ;RETARDO DE 1 SEG		
		TSTFSZ	CONT
		BRA	DEC_HEX
		BRA	PREG_0	
	DEC_HEX	DECF	CONT,1
		DECF	CONT,1	
		BRA	SEGUIR
	;-----------------------------------------------
	;RETARDO DE 1 SEG
	RET_1S	MOVLW	D'498'
		MOVWF	R_1M
	BUCLE	NOP	
		DECFSZ	R_1M,1
		BRA	RET_1M
		RETURN	
	RET_1M	MOVLW	D'498'
		MOVWF	R2_1M
	BUCLE2	NOP
		DECFSZ	R2_1M,1
		BRA	BUCLE2
		BRA	BUCLE
	;-----------------------------------------------	
	RESET_P	MOVLW	0x3F		
		MOVWF	PORTB
		BRA	PREG_0
		END